#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct rgba {
	float	r,
		g,
		b,
		a;
};

layout(std140, binding = 0) buffer buf
{
   rgba imageData[];
};

void main() {
	imageData[gl_GlobalInvocationID.x].r = 1.0 * (gl_GlobalInvocationID.x%1024) / 1024.0;
	imageData[gl_GlobalInvocationID.x].g = imageData[gl_GlobalInvocationID.x].b = imageData[gl_GlobalInvocationID.x].a = 0.0;
}

